#!/usr/bin/env bash

set -ex

java -jar \
/aind-bigstitcher-qc/code/bigstitcher-qc/target/bigstitcher-qc-1.0.0-SNAPSHOT.jar \
$1 \
/results/out \
--anisotropy $2 \
--downsampling $3 \
--interpolation $4
--max-downsampling-levels $5
--display-max $6
